language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - rey.webhouse.net
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- openssl aes-256-cbc -K $encrypted_9ed7e2f87d1c_key -iv $encrypted_9ed7e2f87d1c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/service-deploy.sh dev $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: bash scripts/service-deploy.sh master $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - cb@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: Oryw0R5XIJGDmrspOfUVLXf53CaxiZSx4e1TTE8H3Z8bl8yJdM/mz17LTWJD06m0cMUQv0Bai5Wv1eYDxlTg2wdTAVTqzaw107JuKlR02aN5hxplBweoz3Pbpp2BE95nNmH3+hnUMvoSNlogzNy4Y3Ptv1/bdni1dv5MOwSckvLfw2QcAVvCSS7eDB6MYGM/ifi351Sv5gsJ4IQYbnvdO6DlFTv7e6vkefDyDoUre/EnNMLspiClIjzKYrppA9GRFrQxEwOkeHCyGFZ+1CdZSKwvs8BV7QU2z6Sw2nQ9WwqAJDJ8izUQLaT9047rDQLp/RYYrS38qhLpVwMJj6maw+GLqaA43FAFL43WwYP5wYc+UjJR7HmKRaeYcXUjvWSXPWg7SD7Y3AzrqaQ7ChC2oxrb7LRXa4CDeMdzIyBD4q8eagiW+8PE1+yOBRdrMA2zZSsbwzWIOb/fZmVJ6OveZKkCaybbipN9ErUBIb4yEpRTI2bjD2/2hk8fF6cx2jnVnvoK3FYoOFwxqoMMu6HGZ1l4CQUzan3AZgMp20/QzWZJVGNOk/guDOqzM2RKawTGnvkPEsg7VllacY7cvxYWL7ZTwFHv02N1KkjMe3Kq/kq3IdeOXKb0AWSyMKmRbjaqO5hOScvLaHOcha9rt4OarbOWibvipMRyA9xx0wZVKy8=
