#!/bin/bash

clear

service_name=senti-act-mock-server.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/act/mock-server/production

service=$service_dir/$service_name

echo Registering Senti mock-server service for production ...


if [ ! -e "$service" ]; then
	echo
    echo "Senti mock-server service is not installed"
	echo "Installing Senti mock-server service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl start $service_name
else
    echo "Senti mock-server service is already installed"
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi
